apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-02-19T15:46:53Z"
  labels:
    app: webapp-deployment
  name: webapp-deployment
  namespace: default
  resourceVersion: "54035"
  uid: 9c4654cb-899f-4f50-a7b8-5b9defef2019
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.106.244.220
  clusterIPs:
  - 10.106.244.220
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32503
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: webapp-deployment
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
